### PR TITLE
Keep tarballs for at least 90 days

### PR DESCRIPTION
**Pull request by matyasselmeci**
Per request from @brianhlin

### CODE REVIEW

**Comment by brianhlin** [comment]
To put a finer point on this, I think we should be keeping daily tarballs around until a new release tarball is ready

**Comment by matyasselmeci** [comment]
That's going to be trickier to implement and should go in a ticket.

**Comment by brianhlin** [comment]
I'm fine with approximating it based on number of days and assuming that HTCSS can release new tarballs once every X days. And honestly what we really want to see is:

> tarballs are kept for X days after a release

Because there's often lag between official release and the OSG release. I can imagine instances where Ops is depending on a daily tarball for 9.0.x, a new 9.0.x+1 tarball gets released, but OSG can't release/Ops can't update due to other issues in 9.0.x+1. So they can't get the new tarball until HTCSS applies a fix and waits a day for daily tarball generation. 9.0.0 is a good example of this!

**Comment by matyasselmeci** [comment]
So @timtheisen should we merge this?

**Comment by timtheisen** [comment]
We discussed this change at the flightworthy meeting yesterday. We are concerned this will cause the tarball area to grow too large for the AFS volume. We talked about a split horizon where Linux tarballs would be kept longer and Windows and Mac tarballs would be removed earlier.

**Comment by matyasselmeci** [comment]
OK, I will close this.

**Pull request closed without merging**
